# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/openjdk:8u265-jdk-browsers
    working_directory: ~/repo
    environment:
    # get from git and get maven dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Get chrome version
          command: google-chrome --version
      #- run:
      #    name: Setting chmod for Chrome
      #    command: chmod 777 src/test/resources/webdrivers/linux/chromedriver
      - run:
          name: Running tests
          command: mvn clean install
      - run:
          name: Generate allure report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/
workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
  periodical:
    triggers:
      - schedule:
          cron: "1 4,8,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ui-tests
>>>>>>> feature_branch_2
